/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef VBFHZZ4L_ROOSPINZEROPDF
#define VBFHZZ4L_ROOSPINZEROPDF

#include "RooAbsCategory.h"
#include "RooAbsPdf.h"
#include "RooAbsReal.h"
#include "RooCategoryProxy.h"
#include "RooConstVar.h"
#include "RooDataHist.h"
#include "RooHistFunc.h"
#include "RooRealProxy.h"
#include "RooRealVar.h"

#include "TH3F.h"
#include "TH1.h"

using namespace RooFit;
class VBFHZZ4L_RooSpinZeroPdf : public RooAbsPdf {
protected:

  RooRealProxy kd ;
  RooRealProxy kdint ;
  RooRealProxy ksmd ;
  RooConstVar sigmaioversigma1_HZZ4L;
  RooRealProxy a1, ai;
  RooListProxy _coefList ;  //  List of funcficients
//  TIterator* _coefIter ;    //! Iterator over funcficient lis
  Double_t evaluate() const ;
public:
  VBFHZZ4L_RooSpinZeroPdf() {} ;
  VBFHZZ4L_RooSpinZeroPdf(const char *name, const char *title,
                       RooAbsReal& _kd,
                       RooAbsReal& _kdint,
                       RooAbsReal& _ksmd,
                       RooAbsReal& _a1,
                       RooAbsReal& _ai,
                       const RooArgList& inCoefList);

  VBFHZZ4L_RooSpinZeroPdf(const VBFHZZ4L_RooSpinZeroPdf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new VBFHZZ4L_RooSpinZeroPdf(*this,newname); }
  inline virtual ~VBFHZZ4L_RooSpinZeroPdf() {}

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;
  const RooArgList& coefList() const { return _coefList ; }

  double Integral_T1;
  double Integral_T2;
  double Integral_T3;
  double Integral_T4;
  double Integral_T5;

private:

        ClassDef(VBFHZZ4L_RooSpinZeroPdf,1) // Your description goes here...

};

#endif
