/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Landau core + exponential tail
// Andrea Malara
// 01/08/2019

#include "Riostream.h" 

#include "HiggsAnalysis/CombinedLimit/interface/PolinomialExponent_2p.hpp"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(PolinomialExponent_2p)

PolinomialExponent_2p::PolinomialExponent_2p(const char *name, const char *title, RooAbsReal& _x, RooAbsReal& _e1, RooAbsReal& _e2) :
RooAbsPdf(name,title), x("x","x",this,_x), e1("e1","e1",this,_e1), e2("e2","e2",this,_e2) {
}


PolinomialExponent_2p::PolinomialExponent_2p(const PolinomialExponent_2p& other, const char* name) :
RooAbsPdf(other,name), x("x",this,other.x), e1("e1",this,other.e1), e2("e2",this,other.e2) {
}

Double_t PolinomialExponent_2p::evaluate() const {
  Double_t xp = x/1000.;
  Double_t result = exp(e1*xp+e2*xp*xp);
  return result;
}
