name: clang-tidy-review

on:
  pull_request:
    paths:
      - '**.h'
      - '**.cc'
      - '**.cxx'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v7

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.10.2
        with:
          pixi-bin-path: ${{ github.workspace }}/pixi
          run-install: false

      - name: Run clang-tidy
        uses: ZedThree/clang-tidy-review@v0.23.1
        id: review
        with:
          build_dir: ../build_combine
          split_workflow: true
          config_file: .clang-tidy
          cmake_command: >
            ./pixi run --locked
            cmake -S . -B ../build_combine
            -G Ninja
            -DUSE_VDT=OFF
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Upload artifacts
        uses: ZedThree/clang-tidy-review/upload@v0.23.1
